drivers: fix more build errors
* Use usb_bam.c from the older CAF tag (Nougat).
* Replace log_wakeup_reason(int irq); with log_base_wakeup_reason(irq); as it seems that is newer and that one is being used in O CAF tag.

  LD      init/built-in.o
drivers/built-in.o: In function `msm_pinctrl_resume':
/home/novalineageos/LOS15/out/target/product/hwcan/obj/KERNEL_OBJ/../../../../../../kernel/huawei/msm8953/drivers/pinctrl/qcom/pinctrl-msm.c:991: undefined reference to `log_wakeup_reason'
drivers/built-in.o: In function `smbchg_is_parallel_usb_ok':
/home/novalineageos/LOS15/out/target/product/hwcan/obj/KERNEL_OBJ/../../../../../../kernel/huawei/msm8953/drivers/power/qpnp-smbcharger.c:2413: undefined reference to `get_effective_client_id_locked'
drivers/built-in.o: In function `set_usb_current_limit_vote_cb':
/home/novalineageos/LOS15/out/target/product/hwcan/obj/KERNEL_OBJ/../../../../../../kernel/huawei/msm8953/drivers/power/qpnp-smbcharger.c:2966: undefined reference to `get_effective_client_id_locked'
drivers/built-in.o: In function `__qpnpint_handle_irq':
/home/novalineageos/LOS15/out/target/product/hwcan/obj/KERNEL_OBJ/../../../../../../kernel/huawei/msm8953/drivers/platform/msm/spmi/qpnp-int.c:645: undefined reference to `log_wakeup_reason'
drivers/built-in.o: In function `msm_usb_bam_enable':
/home/novalineageos/LOS15/out/target/product/hwcan/obj/KERNEL_OBJ/../../../../../../kernel/huawei/msm8953/drivers/platform/msm/usb_bam.c:3491: undefined reference to `msm_hw_soft_reset'
/home/novalineageos/LOS15/kernel/huawei/msm8953/Makefile:957: recipe for target 'vmlinux' failed
make[1]: *** [vmlinux] Error 1