sound: use the one from Oreo CAF tag
* The kernel itself is building fine, but errors occurs when building the ROM.
* To fix build errors due the missing formats, like:

hardware/qcom/audio-caf/msm8996/hal/audio_hw.c:3032:68: note: forward declaration of 'struct snd_codec_metadata'
            return out->compr_config.fragment_size - sizeof(struct snd_codec_metadata);
                                                                   ^
hardware/qcom/audio-caf/msm8996/hal/audio_hw.c:5350:38: error: no member named 'flags' in 'struct snd_codec'
            out->compr_config.codec->flags |= COMPRESSED_TIMESTAMP_FLAG;
            ~~~~~~~~~~~~~~~~~~~~~~~  ^
hardware/qcom/audio-caf/msm8996/hal/audio_hw.c:5350:47: error: use of undeclared identifier 'COMPRESSED_TIMESTAMP_FLAG'
            out->compr_config.codec->flags |= COMPRESSED_TIMESTAMP_FLAG;
                                              ^
hardware/qcom/audio-caf/msm8996/hal/audio_hw.c:5416:48: error: invalid application of 'sizeof' to an incomplete type 'struct snd_codec_metadata'
            out->compr_config.fragment_size += sizeof(struct snd_codec_metadata);
                                               ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
hardware/qcom/audio-caf/msm8996/hal/audio_hw.c:5416:62: note: forward declaration of 'struct snd_codec_metadata'
            out->compr_config.fragment_size += sizeof(struct snd_codec_metadata);
                                                             ^
4 errors generated.

hardware/qcom/audio-caf/msm8996/hal/audio_extn/utils.c:1301:14: error: use of undeclared identifier 'SND_AUDIOCODEC_DSD'
        id = SND_AUDIOCODEC_DSD;
             ^
hardware/qcom/audio-caf/msm8996/hal/audio_extn/utils.c:1304:14: error: use of undeclared identifier 'SND_AUDIOCODEC_APTX'
        id = SND_AUDIOCODEC_APTX;
             ^