drivers: power: add pmic-voter.h from the older CAF
* Fix build error:
  CC      drivers/platform/msm/msm_bus/msm_bus_client_api.o
/home/novalineageos/LOS15/kernel/huawei/msm8953/drivers/power/qpnp-smbcharger.c:41:24: fatal error: pmic-voter.h: N
o such file or directory
include "pmic-voter.h"

* There is a pmic-voter.h located in include/linux and i could modify the include, but it is different and since qpnp-smbcharger is from stock (for now)...